'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("xor3.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Module qq1 
        '''
        '''&apos; =====================================================
        '''&apos; VB.NET String Obfuscator v2 by Fathurion
        '''&apos; https://github.com/fathurion/VB.NET-String-Obfuscator
        '''&apos; =====================================================
        '''&apos; Obfuscated string dictonary:
        '''.
        '''</summary>
        Friend ReadOnly Property dic() As String
            Get
                Return ResourceManager.GetString("dic", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to     Public Function ob1(ByVal ob2 As String, ByVal ob3 As String) As String
        '''        Dim ob4 As Byte() = Convert.FromBase64String(ob2)
        '''        Dim ob5() As Byte = System.Text.Encoding.UTF8.GetBytes(ob3)
        '''        Dim obhaha(ob4.Length - 1) As Byte
        '''        For i As Integer = 0 To ob4.Length - 1
        '''            obhaha(i) = ob4(i) Xor ob5(i Mod ob5.Length)
        '''        Next
        '''        Return System.Text.Encoding.UTF8.GetString(obhaha)
        '''    End Function
        '''
        '''    Public Function ob6(ByVal ob7 As String) As String
        '''        [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property plains() As String
            Get
                Return ResourceManager.GetString("plains", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
